# Guardfile for Exercism.io 

require "guard/guard"

module ::Guard
  class Haskell < Guard
    def initialize(watchers=[], options=[]) @options = options; super(watchers, options) end
    # def run_on_change(paths) paths.each do |path| run(path) end end
    # def run_on_additions(paths) run_on_change(paths) end
    def run_on_change(paths) run_all end
    def run_on_additions(paths) run_all end
    def start() run_all end
    def run_all() Dir["*_test.hs"].each do |path| run(path) end end
    def run(path)
      cmd = "echo ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\ntime runghc"
      cmd << " #{@options[:cli]}" if @options[:cli]
      cmd << " #{path}"
      puts cmd; system cmd
    end
  end
end

guard "haskell" do
  watch(%r{.*\.hs$})
end
